apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: db
          image: kiss04/gestion-produits-mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "gestion_produits"
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php-app
spec:
  replicas: 3  # Trois réplicas pour l'évolutivité
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: kiss04/gestion-produits-php5:latest
          env:
          - name: DB_HOST
            value: "db"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "root"
          - name: DB_DATABASE
            value: "gestion_produits"
          ports:
          - containerPort: 80
          volumeMounts:
            - name: php-persistent-storage
              mountPath: /var/www/html/uploads
      volumes:
        - name: php-persistent-storage
          persistentVolumeClaim:
            claimName: php-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi