apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql-app  
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None 

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-app  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Le service est exposé en NodePort
