name: devops

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: kiss04
  MYSQL_IMAGE: kiss04/gestion-produits-mysql
  PHP_IMAGE: kiss04/gestion-produits-php5
  MYSQL_VERSION: latest
  PHP_VERSION: latest
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push-mysql:
    name: Build & Push MySQL Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push MySQL Image
        run: |
          docker build -t $MYSQL_IMAGE:$MYSQL_VERSION ./database
          docker push $MYSQL_IMAGE:$MYSQL_VERSION

  build-and-push-php:
    name: Build & Push PHP Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push PHP Image
        run: |
          docker build -t $PHP_IMAGE:$PHP_VERSION ./www
          docker push $PHP_IMAGE:$PHP_VERSION

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    needs: [build-and-push-mysql, build-and-push-php]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ env.KUBECONFIG_FILE }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f kubernetes/Deployment.yaml
          kubectl apply -f kubernetes/Service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
